name: test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  zig:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Zig version
        run: zig version

      - name: Restore Zig cache
        uses: actions/cache@v2
        with:
          path: zig-cache
          key: ${{ runner.os }}-zig-${{ hashFiles('build.zig') }}
          restore-keys: ${{ runner.os }}-zig-

      - name: Run tests
        run: zig build test
